spring.application.name: gateway-service
eureka.instance.instance-id: ${spring.application.name}:${random.uuid}
spring.cloud.gateway.routes:
  - id: product-service
    uri: lb://product-service
    predicates:
      - Path=/products
