spring.application.name: product-service
server.port: 0
management.endpoints.web.exposure.include: '*'
eureka.instance.instance-id: ${spring.application.name}:${random.uuid}
spring.config.import: optional:configserver:http://localhost:8888
spring.kafka.bootstrap-servers: http://localhost:9092
