spring.application.name: config-server
server.port: 8888
management.endpoints.web.exposure.include: '*'
spring.cloud.config.server.git:
  default-label: main
  uri: https://github.com/dymitr-dev/microservice-architecture
  search-paths: config
spring.kafka.bootstrap-servers: http://localhost:9092
